obj-$(CONFIG_PANEL_GENERIC_DPI) += panel-generic-dpi.o
obj-$(CONFIG_PANEL_LGPHILIPS_LB035Q02) += panel-lgphilips-lb035q02.o
obj-$(CONFIG_PANEL_SHARP_LS037V7DW01) += panel-sharp-ls037v7dw01.o
obj-$(CONFIG_PANEL_NEC_NL8048HL11_01B) += panel-nec-nl8048hl11-01b.o

obj-$(CONFIG_PANEL_TAAL) += panel-taal.o
obj-$(CONFIG_PANEL_TPO_TD043MTEA1) += panel-tpo-td043mtea1.o
obj-$(CONFIG_PANEL_ACX565AKM) += panel-acx565akm.o

obj-$(CONFIG_PANEL_TC358765) += panel-tc358765.o

## LGE_SJIT_S 2011-08-29 [choongryeol.lee@lge.com] Port on K3.0
obj-$(CONFIG_PANEL_LGHDK) += panel-lghdk.o
obj-$(CONFIG_PANEL_LH430WV4_SD02) += panel-lh430wv4-sd02.o
obj-$(CONFIG_PANEL_TX11D101VM_0EAA) += panel-tx11d101vm-0eaa.o
obj-$(CONFIG_PANEL_DX11D100VM) += panel-dx11d100vm.o
obj-$(CONFIG_PANEL_TX11D108VM_0BAA) += panel-tx11d108vm-0baa.o
obj-$(CONFIG_PANEL_HX8389) += panel-hx8389.o
obj-$(CONFIG_PANEL_LH430WV2_SD01) += panel-lh430wv2-sd01.o
## LGE_SJIT_E 2011-08-29 [choongryeol.lee@lge.com] Port on K3.0
