obj-$(CONFIG_LGE_BROADCAST_TDMB_TCC3170)   += tcbd_fic_decoder.o

EXTRA_CFLAGS += -Idrivers/broadcast/tdmb/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/broadcast/tdmb/tcc3170/inc/tcbd_fic_decoder
EXTRA_CFLAGS += -Idrivers/broadcast/tdmb/tcc3170/inc/tcpal
