#
# Makefile for the LGE u2 board
#

obj-y += u2.o \
		 u2_i2c.o \
		 u2_mux.o \
		 u2_emif.o \
		 u2_pdev.o \
		 u2_mmc.o \
		 u2_spi.o \
		 u2_power.o \
		 u2_display.o \
		 u2_keypad.o \
		 u2_cmdline.o \
		 u2_misc.o
