#
# Makefile for the LGE cx2 board
#

#[SJIT] mohamed.khadri@lge.com - Added wifi control device for BCM4330
obj-y += ../board-lg-wifi.o

obj-y += cx2.o \
		 cx2_i2c.o \
		 cx2_mux.o \
		 cx2_emif.o \
		 cx2_pdev.o \
		 cx2_mmc.o \
		 cx2_spi.o \
		 cx2_power.o \
		 cx2_display.o \
		 cx2_keypad.o \
		 cx2_cmdline.o \
		 cx2_misc.o
