#
# Makefile for the broadcast(TDMB) RF/BB core.
#

obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= broadcast_tdmb_drv_if.o
#obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= fc8050/
#obj-$(CONFIG_LGE_BROADCAST_TDMB)		+= lg2102/
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= t3900/
#obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= t39fx/
obj-$(CONFIG_LGE_BROADCAST_TDMB_TCC3170)	+= tcc3170/