#
# Makefile for the TDMB T39F0 drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= broadcast_t39fx_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= broadcast_t39fx.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= tdmb_tunerbbdrv_t39fx.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= INC_INTERFACE.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= INC_PROCESS.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= INC_FICDEC.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= INC_QFIFO.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T39FX)		+= INC_RF_CTRL500.o

#obj-y		+= broadcast_t39fx_drv_if.o
#obj-y		+= broadcast_t39fx.o
#obj-y		+= tdmb_tunerbbdrv_t39fx.o
#obj-y		+= INC_INTERFACE.o
#obj-y		+= INC_PROCESS.o
#obj-y		+= INC_FICDEC.o
#obj-y		+= INC_QFIFO.o
#obj-y		+= INC_RF_CTRL500.o