obj-$(CONFIG_LGE_BROADCAST_TDMB_TCC3170)   += tcbd_diagnosis.o

EXTRA_CFLAGS += -Idrivers/broadcast/tdmb/tcc3170/inc
EXTRA_CFLAGS += -Idrivers/broadcast/tdmb/tcc3170/inc/tcpal
EXTRA_CFLAGS += -Idrivers/broadcast/tdmb/tcc3170/inc/tcbd_diagnosis
