obj-$(CONFIG_LG_FW_MAX17043_FUEL_GAUGE_I2C)   	+= max17043_fuelguage_i2c.o
obj-$(CONFIG_LG_FW_MAX17043_FUEL_GAUGE_GPIO)   	+= max17043_fuelguage_gpio.o
obj-$(CONFIG_LG_FW_MAX17040_FUEL_GAUGE)   	+= max17040_battery.o
obj-$(CONFIG_LG_FW_STC3105_FUEL_GAUGE)   	+= stc3105_battery.o
obj-$(CONFIG_LG_FW_MAX17048_FUEL_GAUGE_I2C)   	+= max17048_fuelguage_i2c.o
