#
# Makefile for the TDMB T3900 drivers.
#

# Each configuration option enables a list of files.
# LGE
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= broadcast_t3900_drv_if.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= broadcast_t3900.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= tdmb_tunerbbdrv_t3900.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= INC_INTERFACE.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= INC_PROCESS.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= INC_FICDEC.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= INC_QFIFO.o
obj-$(CONFIG_LGE_BROADCAST_TDMB_T3900)		+= INC_RF_CTRL500.o
