#
# Makefile for the LGE p2 board
#

obj-y += p2.o \
		 p2_i2c.o \
		 p2_mux.o \
		 p2_emif.o \
		 p2_pdev.o \
		 p2_mmc.o \
		 p2_spi.o \
		 p2_power.o \
		 p2_display.o \
		 p2_keypad.o \
		 p2_cmdline.o \
		 p2_misc.o
