#
# Makefile for the LGE HDK board
#

obj-y += lghdk.o \
		 lghdk_i2c.o \
		 lghdk_mux.o \
		 lghdk_keypad.o \
		 lghdk_emif.o \
		 lghdk_mmc.o \
		 lghdk_power.o \
		 lghdk_display.o \
		 lghdk_pdev.o \
		 lghdk_misc.o
